# api.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-leijin
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: nathansegers/containers_23-24_december_api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-configmap
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/src/config/config.json # Updated mount path
          resources: {} # Move resources here
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: api-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8001
      targetPort: 80
      nodePort: 30000
