apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-leijin
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3d-k3s-default-agent-2
      containers:
        - name: frontend-demo
          image: nathansegers/containers_23-24_december_frontend
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-configmap
          # env:
          #   - name: API_PORT
          #     value: '8001'
          #   - name: API_HOST
          #     value: 'api-service'
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'
            requests:
              cpu: '0.1'
              memory: '256Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-leijin
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
