# version: '3.9'

# services:
#   web:
#     build: ./pointsApp
#     ports:
#       - '5000:5000'
#     env_file: .env
#     depends_on:
#       - db
#     networks:
#       - web
#       - database

#   db:
#     image: ghcr.io/eslih/postgres:16.1-alpine
#     env_file: .env
#     networks:
#       - database

# networks:
#   web:
#   database:
version: '3.9'

services:
  web:
    build: ./pointsApp
    ports:
      - '5000:5000'
    env_file: .env
    depends_on:
      - db
    networks:
      - web
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    env_file: .env
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "student", "-d", "points", "-h", "db"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web:
  database:
